### ISSUE TITLE
Revamp Mul, Ldiv, and Inv as Applied

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaArrays/LazyArrays.jl#11]
A more general approach is to support general application of functions. The current lazy operations could be type aliases.

**Comment by dlfivefifty** [comment]
@tkf This would mean we have the option of the following type aliases:
```julia
const Mul = Applied{typeof(*)}
const Ldiv = Applied{typeof(\)}
const PInv = Applied{typeof(pinv)}
const Inv = Applied{typeof(inv)}

const Plus = Applied{typeof(+)}
```
The last one is tricky because we have the choice between `Applied` and `Broadcasted` because they  mean the same thing here. I forgot why we decided to leave `Plus` as a `BroadcastArray{typeof(+)}` instead of a `Broadcasted`, but maybe `Applied` solves the same problem?

**Comment by tkf** [comment]
Cool!  It looks like LazyArrays is becoming a fully customizable computation graph library.

Re: `Plus`.  I'm not sure what's the best way, but here is an observation: `ones(3,3) + I` works but `ones(3,3) .+ I` does not.  Lazy expression involving `UniformScaling` sounds very useful.  Doing so with `Broadcasted` would be incompatible with standard broadcasting implementation (at least ATM).  So, maybe `Applied` is better so that we can do more advanced stuff without breaking the semantics of `Broadcasted`?
