### ISSUE TITLE
Move out `Applied` to separate package, LazyApplying.jl

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaArrays/LazyArrays.jl#117]
@tkf Do you agree this is a good idea? 

I think the `Applied` type isn't actually necessary for `ApplyArray`, and the current setup feels a bit messy.

**Comment by tkf** [comment]
My worry would be that going to fully `Abstractarray`-based interface would make it impossible to create a well-defined interface because you need to rely on `return_type` (whose exact result is undefined).  Yes, I know `Base`/stdlib use it but that's not the best reason to not aim higher.

That said, since I haven't contributed much to this package and I don't feel I know practical implementation problems enough, I have no objection if you want to separate out `Applied` from LazyArrays.jl.

**Comment by dlfivefifty** [comment]
I meant it would essentially work as is, so the macro stuff (which you are right, you don't want to depend on `return_type`) would be in LazyApplying.jl. 

But maybe there's a half-way step that will do what I want. My main issue is that the call tree for `*(::LazyArray, ::LazyArray)` is quite complicated, and could instead just use the `LayoutArray` version from ArrayLayouts.jl, which only uses `MemoryLayout` to decide how multiplication should behave.

Though there is still the issue of `*(::LazyArray, ::LazyArray, ::LazyArray)`, that is, three (or more) multiplications. I think I'll have to think about it a bit more.

**Comment by tkf** [comment]
Don't you need `return_type` for something equivalent to `LazyArray(Mul(...))`?  Does ArrayLayouts.jl handle it differently?

https://github.com/JuliaArrays/LazyArrays.jl/blob/b40c250270f3b0c40f341f01701896fd87089593/src/linalg/mul.jl#L34

(I'd imagine getting rid of this would require a huge overhaul of LinearAlgebra.jl, though.)

**Comment by dlfivefifty** [comment]
Actually you are right
